[2025-08-18T02:48:27.691+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-18T02:48:27.815+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.run_dbt_transformations manual__2025-08-18T01:29:52.036937+00:00 [queued]>
[2025-08-18T02:48:27.820+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.run_dbt_transformations manual__2025-08-18T01:29:52.036937+00:00 [queued]>
[2025-08-18T02:48:27.820+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-18T02:48:27.828+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_dbt_transformations> on 2025-08-18 01:29:52.036937+00:00
[2025-08-18T02:48:27.835+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'run_dbt_transformations', 'manual__2025-08-18T01:29:52.036937+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/weather_dags.py', '--cfg-path', '/tmp/tmpbhiv1uls']
[2025-08-18T02:48:27.837+0000] {standard_task_runner.py:91} INFO - Job 69: Subtask run_dbt_transformations
[2025-08-18T02:48:27.837+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=253) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-18T02:48:27.838+0000] {standard_task_runner.py:63} INFO - Started process 255 to run task
[2025-08-18T02:48:27.878+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_pipeline.run_dbt_transformations manual__2025-08-18T01:29:52.036937+00:00 [running]> on host b10b13b5f146
[2025-08-18T02:48:27.953+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Hendi Irwanto' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='run_dbt_transformations' AIRFLOW_CTX_EXECUTION_DATE='2025-08-18T01:29:52.036937+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-18T01:29:52.036937+00:00'
[2025-08-18T02:48:27.953+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-18T02:48:27.962+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-18T02:48:27.963+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --project-dir /opt/data-engineer/weather-project/dbt/weather_dbt --profiles-dir /opt/data-engineer/weather-project/dbt/weather_dbt/.dbt']
[2025-08-18T02:48:27.971+0000] {subprocess.py:86} INFO - Output:
[2025-08-18T02:48:29.777+0000] {subprocess.py:93} INFO - [0m02:48:29  Running with dbt=1.10.7
[2025-08-18T02:48:30.078+0000] {subprocess.py:93} INFO - [0m02:48:30  Registered adapter: postgres=1.9.0
[2025-08-18T02:48:30.343+0000] {subprocess.py:93} INFO - [0m02:48:30  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-08-18T02:48:30.343+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-08-18T02:48:30.343+0000] {subprocess.py:93} INFO - - models.dbt_date
[2025-08-18T02:48:30.498+0000] {subprocess.py:93} INFO - [0m02:48:30  Found 5 models, 2 sources, 576 macros
[2025-08-18T02:48:30.500+0000] {subprocess.py:93} INFO - [0m02:48:30
[2025-08-18T02:48:30.500+0000] {subprocess.py:93} INFO - [0m02:48:30  Concurrency: 1 threads (target='dev')
[2025-08-18T02:48:30.501+0000] {subprocess.py:93} INFO - [0m02:48:30
[2025-08-18T02:48:30.591+0000] {subprocess.py:93} INFO - [0m02:48:30
[2025-08-18T02:48:30.591+0000] {subprocess.py:93} INFO - [0m02:48:30  Finished running  in 0 hours 0 minutes and 0.09 seconds (0.09s).
[2025-08-18T02:48:30.592+0000] {subprocess.py:93} INFO - [0m02:48:30  Encountered an error:
[2025-08-18T02:48:30.592+0000] {subprocess.py:93} INFO - Database Error
[2025-08-18T02:48:30.592+0000] {subprocess.py:93} INFO -   connection to server at "172.18.0.2", port 5432 failed: FATAL:  password authentication failed for user "noc"
[2025-08-18T02:48:30.592+0000] {subprocess.py:93} INFO - 
[2025-08-18T02:48:31.849+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-08-18T02:48:31.850+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-18T02:48:31.861+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-08-18T02:48:31.863+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_data_pipeline, task_id=run_dbt_transformations, run_id=manual__2025-08-18T01:29:52.036937+00:00, execution_date=20250818T012952, start_date=20250818T024827, end_date=20250818T024831
[2025-08-18T02:48:31.871+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 69 for task run_dbt_transformations (Bash command failed. The command returned a non-zero exit code 2.; 255)
[2025-08-18T02:48:31.891+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-18T02:48:31.909+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-18T02:48:31.910+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
