[2025-08-18T01:26:49.538+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-18T01:26:49.666+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.fetch_weather_data scheduled__2025-08-17T00:00:00+00:00 [queued]>
[2025-08-18T01:26:49.672+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.fetch_weather_data scheduled__2025-08-17T00:00:00+00:00 [queued]>
[2025-08-18T01:26:49.672+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 5
[2025-08-18T01:26:49.679+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_weather_data> on 2025-08-17 00:00:00+00:00
[2025-08-18T01:26:49.686+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'fetch_weather_data', 'scheduled__2025-08-17T00:00:00+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/weather_dags.py', '--cfg-path', '/tmp/tmpyro84hu3']
[2025-08-18T01:26:49.688+0000] {standard_task_runner.py:91} INFO - Job 59: Subtask fetch_weather_data
[2025-08-18T01:26:49.688+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=449) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-18T01:26:49.688+0000] {standard_task_runner.py:63} INFO - Started process 451 to run task
[2025-08-18T01:26:49.732+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_pipeline.fetch_weather_data scheduled__2025-08-17T00:00:00+00:00 [running]> on host 23863237c1a1
[2025-08-18T01:26:49.809+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Hendi Irwanto' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='fetch_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-17T00:00:00+00:00'
[2025-08-18T01:26:49.810+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-18T01:27:09.895+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-08-18T01:27:09.895+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-08-18T01:27:09.897+0000] {process_utils.py:132} INFO - Sending 15 to group 451. PIDs of all processes in the group: [451]
[2025-08-18T01:27:09.897+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 451
[2025-08-18T01:28:09.920+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=451, name='airflow task ru', status='sleeping', started='01:26:49') did not respond to SIGTERM. Trying SIGKILL
[2025-08-18T01:28:09.920+0000] {process_utils.py:87} INFO - Sending the signal 9 to group 451
[2025-08-18T01:28:09.927+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=451, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='01:26:49') (451) terminated with exit code -9
[2025-08-18T01:28:09.928+0000] {standard_task_runner.py:178} ERROR - Job 59 was killed before it finished (likely due to running out of memory)
